import React,  {useState, useEffect} from 'react';
import Circles from './Components/Circles'
import Diary from './Components/Diary'
import Dialogue from './Components/Dialogue'
import { View, Text, StyleSheet, Button, TouchableOpacity, ScrollView } from 'react-native';
function App() {
   const [totalRecords, setTotalRecords] = useState([
    {"title": "My dog won't look at me", "trigger": "Rundown", "day": "05-06-2021", "story": "This started a few weeks ago. I had a friend and her kids stay with me and my wife for a few days. Hadn’t seen them in awhile and they had never been to Texas (we are from California and they are originally from Thailand but we met in California years back). We showed them some of the unique things about Texas eg bbq, bucees, etc. Anyway while they were here we started talking about eating different things from different countries and she asks if I have ever eaten bugs. I have but only once but I’m open to try anything once. Fast forward to this morning. I’m laying in bed and my wife goes to get the mail. She hands me a padded envelope and says it’s from (friend). No idea what it could be so I tear open the package. Our dog was very interested btw. I get a smell like nuts so I’m thinking ‘strange she would send me nuts’ when a few fall out onto my shirtless torso and on the bed. They’re very black and now I’m more confused. Then I focus on one and I realize it’s a cricket body. She sent me fried crickets. One of the bags must have broken open in transit so they’re falling all over the place and my wife is losing her SHIT screaming about bugs in the bed. I am laughing hysterically picking cricket parts out of my chest hair while she runs away making a combination of screaming, laughing, and gagging sounds."},
    {"title": "Rude Coworkers", "trigger": "Fear", "day": "06-12-2021", "story": "Today was my first day back from 13 days of isolation. I was very sick from Covid along with 18 others from one area -- about 1/5th the workforce. The young lady who watered my plants in my lab was asking how I was doing and how I felt being back when another co-worker, a Karen-esque type, came up to us. She interrupted me to tell us how upset she is that so many people are out and how much extra work she has to do. I told her I had been out because sometimes people get sick and they need to take time off, and the mandates in our state require those who test positive to quarantine for 10 days. She then exclaimed, pointing her bony finger angrily at me, 'so, you're the damn superspreader!' I said to her 'no, I wasn't, but I heard that was your nickname in high school.' I had to visit HR after lunch. I was told my comment wasn’t appreciated and not to do it again."},
    {"title": "Curse of the Bean Juice", "trigger": "Ambiguity", "day": "08-24-2021", "story": "A few weeks ago I bought some dried garbanzo beans. I hate how long it takes dried beans to cook so I decided to presoak them in a canning jar. In my infinite wisdom I thought 'canned beans don't need to be refrigerated so these shouldn't be any different.' This morning I noticed there were bubbles coming out of the jar in my pantry. This is when I realized maybe I should have refrigerated them I also noticed the lid of the jar was bulging out so I knew it had some pressure built up inside. I'm guessing they started to ferment. I didn't want to open it up right away so I thought I would relive the pressure before opening to throw them away. I took a thumbtack and poked a hole in the lid of the jar. As soon as I took the tack out a geyser of shit smelling bean water shot up to my ceiling. This was the most foul smelling thing I have ever smelled and it covered my kitchen with this rancid bean juice. As I am typing this my wife has left me to clean my shame while she hides in the bathroom (the only room spared from the stink)."},
    {"title": "My dog and my phone", "trigger": "Ambiguity", "day": "09-02-2021", "story": "For context my dog is a 5 month old Greyhound cross Labrador and is very tall. She is normally well behaved, and since she was tired I left my phone on the shelf (I did not know she could reach it) to get a glass of water. I was gone for maximum 30 seconds but when I got back she was not there. At this point I had not realised that my phone was gone, so I went into the garden to check what she was doing. To my horror she had it in her mouth and was throwing it around in the garden. For some reason I thought it would be a good idea to chase after her, which of course made her run off with the phone thinking we were playing a game. Only then I thought to tell her to drop it - at which point she happened to be stood right in front of a pile of her own excrement. You can guess what happened next. She then decided to stand on it, smearing shit all over the screen. As I picked it up she gave me a look that I can only describe as a 'fuck you,' and I proceeded to spend a very long time scraping droppings off my phone."},
    {"title": "The freaking fire alarm", "trigger": "Rundown", "day": "09-16-2021", "story": "I’m a senior in college and live with 2 other girls in a student only apartment off campus. For whatever reason I never outgrew wetting the bed and do it almost every night. Up until today I’ve done a pretty good job at hiding it. I change into a diaper at night in my own room and in the morning I stash the used diaper in a large bag I and throw it out in the apartment complex dumpster on my way out. No one other than my ex boyfriend has ever found out about my issues. I live in a hot state and it gets warm at night, no one sees me so I wore these little booty shorts and a tank top to bed. Then, at 3:00 am the fire alarm goes off. I wake up groggy and hear people evacuating the building, and me and my roommates start to head outside too. It’s not until I’m almost out the door that I realize what I’m wearing. Keep in mind, these are not Depend that advertise how discreet they are under yoga pants. These are made for bedwetting. They’re geriatric, tape-on incredibly thick and high waisted diapers, and not to be gross but it was wet too which makes it thicker. The waistband was peeking above my pants and the bulk clearly showed through the thin fabric of my shorts. I tried to yank my tank top down as far as I could, but it still didn’t meet the waistband of my shorts. I thought if I didn’t draw attention to it, maybe no one would notice. That is until I heard a guy in a group of about 10 people behind me whisper “I think that chicks wearing a diaper” a couple of people did a light gasp and giggle and I heard one girl say “oh my god, not so loud, she must be so embarrassed.” I turned around instinctively at the group and one girl said to me “cute shorts” and a couple more of them giggled. I was beyond humiliated and turned bright red. That’s when my roommates both looked down and saw the mess that was my lower half. One of them went silent and her eyes went as wide as saucers. My other roommate took off her robe (she was also wearing pajamas) and handed it to me and said “here you look really cold.” I then put on the robe and waited what seemed like an eternity until they let us in the building. As I was walking upstairs I heard someone below us in that same group ask “so was that girl seriously wearing a diaper” and someone responded “yeah I think she was. This happened a couple days ago and no one has said anything to me sense, but I have never been so embarrassed in my life."},
    {"title": "I missed my chance", "trigger": "Fear", "day": "09-21-2021", "story": "So this happened this summer but the full realization of what happened didn't hit me until recently. For some context I am a 20 y/o male college student and I was working a summer job which is where I met this girl. She had been working there for about 2 years with me but it wasn't until this past summer we really started to make a connection. Most of our interactions while working or on break were always great and we seemed to have a certain sort of chemistry. Then in the latter half of summer she left that job to go somewhere more related to her field of study. Before she did however, she gave me her snap so we could keep in touch which we did. For a while after she left we snapped often, mostly chatting and small talk. On more than one occasion she invited me to come over her house to hang out (she lived with her family still). Sometimes I had other prior commitments so I couldn't make it but other times I just felt too nervous about going over her house by myself that I made up excuses and stayed home. At one point she literally hit me with the ‘my parents aren't home’ bit and I completely brushed it off and claimed I had ‘something else to go to’. Anyway, we start approaching the start of school and I head back to college, but we still have been chatting in the time being. Once the first week of classes hit however, she just stopped responding to my messages. I figured she was busy with classes but after a while (several weeks) of me sending the occasional snap or ‘hey’ with no response I realized she had most likely ghosted me. I didn't grasp the severity of how bad I screwed up until I recently had a 2 am realization like we all do."},
    {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "09-30-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."},
    {"title": "Kung Fu Embarassment", "trigger": "Rundown", "day": "10-09-2021", "story": "So this happened in 2015 i was 9 years old i joined a kung fu academy because i liked martial arts so basically what happened is that i used to excercise in tracksuit before in kung fu class i excitedly bought a new uniform for my class so the first day of class with uniform we doing some sort of strectching there were girls behind me and suddenly i hear a ‘tsshhhhhhh’ sound i was like Wtf but i kept stretching i heard girls behind me laughing i thought maybe they were laughin bout somethin else suddenly they called the teacher and he suddenly stopped me cuz my ass was showing from behind and he says me to go rest i said’ why' he says : ‘go rest its enough ‘ OnLy Me i was likeee WTF suddenly he called my parents and told him and then i got to know what that ‘tsshhh’ sound was he got me home i was crying with embarassment . But i still had the courage to back to class days later."},
    {"title": "Diffusing with Humor Fail", "trigger": "Goals", "day": "10-13-2021", "story": "Long story short, my dumbass self thought it would be a great idea to be the funny guy and deliberately put a slightly offensive joke in an oral case study presented to the dean. At some point I was talking about dwarf people and the discriminations they're facing, so I added: ‘they're often accused of not measuring up’. (Measuring...they're of short height...got it?). It loses a bit of meaning when translated. IMO it was funnier in French (''on les accuse souvent de ne pas être à la hauteur). A couple of students laughed, the dean took his pen and wrote down a comment disapprovingly. As soon as I had finished, he told me: ''The joke you tried to make was really unwelcome, even calling it a joke is a nice gesture of my part''. Needless to say, this set the mood for the rest of his comments on my case study and now I'm probably seen as a bad troll by the class and the dean himself. So yeah."},
    {"title": "Thought I was a teenager", "trigger": "Fear", "day": "10-14-2021", "story": "It was a normal day at school and the bell to get to class had rung. I was walking back up the school from my truck. It's only about 100 yards or so. As I'm nearing the school my friend rolls up in her mini van and stops to give me the bird. As friends do. As a joke, I flopped on the hood of car belly first, my feet pointing away from the school. She hit the gas and off we went. We traveled about 25 yards and I adjusted myself. She thought I was sliding off and hit the brakes. Well, she has hit them a little too hard and slid. I tried to catch myself on the top edge of the hood but missed and snagged her windshield wiper which didn't hold. So I slid off and my feet hit first. Now, I'm a fairly large guy about 200 lbs. That's alot of weight to get stopped quickly. My ankles were simply not hoss enough to handle it. My feet hit the ground and I thought I heard my boots scrape the ground, in hindsight I think it was my ankles. The area around my ankles went numb and tingly while simultaneously hurting like hell. I tumbled about 5 times hitting my elbow along the way leaving it nice and bruised. I layed out and all I could do was yell in pain. I had bilateral fractures in both of my ankles. Meaning I broke both bones in each ankle totalling out to four bones broke. According to the doc, that was the second worst type of fracture I could've gotten. I destroyed my left ankle joint with the doc pulling out a lot of bone and cartilage fragments. I'm non weight baring for 8-10 weeks. The 8 weeks mark being new years eve."},
    {"title": "Blanket Confusion", "trigger": "Rundown", "day": "10-22-2021", "story": "Yesterday I went to a fabric store and I was in a hurry to get home because I was tired and was up all night so I just wanted to get in and get out but of all the days this small fabric store had to be busy it was today so I go in I get my fabric and realize I got the wrong one so I go back get my fabric again and grab a number I was 86 the were on 84 not so bad but no the lady in front of me had a cart full of Blanket fabric so she needs a lot so I wait in line for like ten minutes she still not done so I text my friend if this lady doesn’t hurry up Going to cuss her out so as I was about to lose my mind when they open a new register so I head on over and hear ‘I’m making blankets for foster kids’"},
    {"title": "Dog and the Amazon Guy", "trigger": "Ambiguity", "day": "10-22-2021", "story": "This actually happened a few weeks ago before Halloween. I have a few of those inflatable halloween lawn decorations and typically when I turn them on and if I happen to have the front window blinds open, my dog will start barking at them since she thinks someone is coming to the house. Well, one of these evenings the blinds were open and she started barking, so to amuse her I said 'let''s go get 'em!' and I opened the front door. Unbeknownst to me, she was actually barking at an amazon delivery guy and when we went out I see a guy hauling butt back to his delivery van. I commanded my dog to stop and go back inside. I then went over to the delivery guy and profusely apologized and told him I wasn't telling my dog to go after him but rather the inflatables, as she always barks at them when I turn them on. He didn't seem too happy, but I kept apologizing for it."},
    {"title": "Toilet Flush with HR", "trigger": "Ambiguity", "day": "10-24-2021", "story": "THANKFULLY this was today so I have a suuuuper fresh recollection of it /s. I work like most people do on Mondays and decided to take my afternoon dump. I had gotten a Fair number of spam calls this morning and was on a hot streak of answering my phone to either silence or someone trying to speak to me who had nothing to do with me. While I was on the toilet, I gotten what I thought was another spam call. I should have recognized the number and realized it was my new employer (start the job in two weeks), but alas was quick to answer after killing it on candy crush. Most people would have just finished the convo on the toilet, but since I hadn't started doing the deed yet, in an effort to have the convo in a respectable area, I got off the toilet and attempted to leave the stall. I forgot that our toilets have the motion sensors that know when someone leaves and as I was exiting the stall, the toilet went off. Here comes the awkward pause from the HR person and I just move forward with the conversation."},
    {"title": "Dangerous Stir Fry", "trigger": "Rundown", "day": "10-27-2021", "story": "Late last night I ate a stir fry and there was this massive bit of brocolli and I just wolfed it down forgetting to chew. It gets stuck in my throat and I start to choke but as if that's not bad enough this bit of brocolli is absolutely roasting and its hurting so much. I start to panic and look for some water or juice in a glass around me but of course there is none cause I'm an idiot and was so focused on getting the food down me as soon as possible I hadn't bothered to get a drink. So I stumble towards the kitchen, tripping over the coffee table and knocking everything flying, my life flashing before my eyes, I smash down the corridor bumping into everything possible, throwing myself into the kitchen I grab a glass of water and after a few attempts manage to slowly swallow this absolutely boiling, massively painful, stupidly chunky piece of brocolli down my throat. I catch my breath, I calm down, I stare at the floor for a while hanging my head, I clean up my mess and I go to bed. All day today I can feel my throat is burnt. Its sore inside and my voice is a little raspy. I knew its possible to choke on your food but I didn't know I could badly burn the inside of my throat. Always remember to chew folks. I think I'll be obsessively blowing on my food before I eat it for the rest of my life now…"},
    {"title": "Where are my keys?", "trigger": "Goals", "day": "10-29-2021", "story": "I work at a doggy daycare in and there’s this one small older dog that we walk for about 15 minutes every day. He has a set of keys we need to use to walk him and if we don’t walk him we get in big trouble with the parents. While normally he only had one walk, today he had two. My shift ended before the second walk so another person was going to do it until they noticed they were missing the keys and texted me. My friend and I had been planning going to a Korean bbq place that has a 30 minute time limit for a while now and I got the text from work 5 minutes after we started eating. The place cost 40 dollars per person plus additional beverages and tip so if I left then I wouldn’t be able to make it in time back as I would be using public transport. It’s also the first time I’ve seen my friend in a month and a half. After a back and forth with my manager and another coworker I thought I would be able to drop it off later on as the coworker told me this but then I got called by my boss who then ordered an Uber so that I could send back the key in my bag despite me saying I could leave immediately. I feel terrible and although I was told that mistakes happen by my boss, the manager did not respond to my further messages so now I believe she highly dislikes me. I was told by someone else that I am already disliked for being picky or bossy so now I’m sure that there is not a single person at work that doesn’t dislike me. I’m also scared for the sanctity of my job."},
    {"title": "My Crush is Cringe", "trigger": "Fear", "day": "10-30-2021", "story": "So this just happened an hour ago and I wanna drown myself. I (15M) had a crush in this girl we’ll call Rose. Recently I finally had the courage to confess to her how I felt and we fortunately ended things on a good note with her saying she’s not ready for a relationship and remained good friends. Things should’ve ended there right? But my stupid self decided no. Jump to today; I was working on my homework while talking to Rose. We were running out of topics to talk about, and I decided to ask ‘When do you think you’re ready for a relationship?’ She just replied she couldn’t imagine herself being in a relationship. Then she asked why I asked. Please keep in mind I was half awake as I was pretty tired. I just responded ‘Just curious, and also since you said you weren’t ready for a relationship so I was thinking I could wait for you to be ready.’ She didn’t reply for a while and 10 minutes later I decided to check our dm and as I was re reading what I sent her, I start realizing what I said was incredibly weird. I decided to delete the message and changed my reply to ‘Donno just curious’ Since discord is an asshole, they don’t show if the other person had read the message or not. So I was hoping she didn’t see it, but I knew I was too far late. I told our mutual friend about it and they said she read it. My. Heart. Stopped. I just wanted to die.. I probably made things worse for us and she wasn’t going to see me the same way ever again. I’ve been typing this out and thinking what I should do. She did reply to me like she didn’t see what happened.. so now im fully awake.. not sure what to do.. I’ll keep you guys updated if anything happens if ya’ll interested Anyways thanks for reading."},
    {"title": "Curse of the Bean Juice", "trigger": "Ambiguity", "day": "10-30-2021", "story": "A few weeks ago I bought some dried garbanzo beans. I hate how long it takes dried beans to cook so I decided to presoak them in a canning jar. In my infinite wisdom I thought 'canned beans don't need to be refrigerated so these shouldn't be any different.' This morning I noticed there were bubbles coming out of the jar in my pantry. This is when I realized maybe I should have refrigerated them I also noticed the lid of the jar was bulging out so I knew it had some pressure built up inside. I'm guessing they started to ferment. I didn't want to open it up right away so I thought I would relive the pressure before opening to throw them away. I took a thumbtack and poked a hole in the lid of the jar. As soon as I took the tack out a geyser of shit smelling bean water shot up to my ceiling. This was the most foul smelling thing I have ever smelled and it covered my kitchen with this rancid bean juice. As I am typing this my wife has left me to clean my shame while she hides in the bathroom (the only room spared from the stink)."},
    {"title": "My dog and my phone", "trigger": "Ambiguity", "day": "10-31-2021", "story": "For context my dog is a 5 month old Greyhound cross Labrador and is very tall. She is normally well behaved, and since she was tired I left my phone on the shelf (I did not know she could reach it) to get a glass of water. I was gone for maximum 30 seconds but when I got back she was not there. At this point I had not realised that my phone was gone, so I went into the garden to check what she was doing. To my horror she had it in her mouth and was throwing it around in the garden. For some reason I thought it would be a good idea to chase after her, which of course made her run off with the phone thinking we were playing a game. Only then I thought to tell her to drop it - at which point she happened to be stood right in front of a pile of her own excrement. You can guess what happened next. She then decided to stand on it, smearing shit all over the screen. As I picked it up she gave me a look that I can only describe as a 'fuck you,' and I proceeded to spend a very long time scraping droppings off my phone."},
    {"title": "The freaking fire alarm", "trigger": "Rundown", "day": "11-01-2021", "story": "I’m a senior in college and live with 2 other girls in a student only apartment off campus. For whatever reason I never outgrew wetting the bed and do it almost every night. Up until today I’ve done a pretty good job at hiding it. I change into a diaper at night in my own room and in the morning I stash the used diaper in a large bag I and throw it out in the apartment complex dumpster on my way out. No one other than my ex boyfriend has ever found out about my issues. I live in a hot state and it gets warm at night, no one sees me so I wore these little booty shorts and a tank top to bed. Then, at 3:00 am the fire alarm goes off. I wake up groggy and hear people evacuating the building, and me and my roommates start to head outside too. It’s not until I’m almost out the door that I realize what I’m wearing. Keep in mind, these are not Depend that advertise how discreet they are under yoga pants. These are made for bedwetting. They’re geriatric, tape-on incredibly thick and high waisted diapers, and not to be gross but it was wet too which makes it thicker. The waistband was peeking above my pants and the bulk clearly showed through the thin fabric of my shorts. I tried to yank my tank top down as far as I could, but it still didn’t meet the waistband of my shorts. I thought if I didn’t draw attention to it, maybe no one would notice. That is until I heard a guy in a group of about 10 people behind me whisper “I think that chicks wearing a diaper” a couple of people did a light gasp and giggle and I heard one girl say “oh my god, not so loud, she must be so embarrassed.” I turned around instinctively at the group and one girl said to me “cute shorts” and a couple more of them giggled. I was beyond humiliated and turned bright red. That’s when my roommates both looked down and saw the mess that was my lower half. One of them went silent and her eyes went as wide as saucers. My other roommate took off her robe (she was also wearing pajamas) and handed it to me and said “here you look really cold.” I then put on the robe and waited what seemed like an eternity until they let us in the building. As I was walking upstairs I heard someone below us in that same group ask “so was that girl seriously wearing a diaper” and someone responded “yeah I think she was. This happened a couple days ago and no one has said anything to me sense, but I have never been so embarrassed in my life."},
    {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "11-02-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."},
    {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "11-02-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."},
    {"title": "Diffusing with Humor Fail", "trigger": "Goals", "day": "11-03-2021", "story": "Long story short, my dumbass self thought it would be a great idea to be the funny guy and deliberately put a slightly offensive joke in an oral case study presented to the dean. At some point I was talking about dwarf people and the discriminations they're facing, so I added: ‘they're often accused of not measuring up’. (Measuring...they're of short height...got it?). It loses a bit of meaning when translated. IMO it was funnier in French (''on les accuse souvent de ne pas être à la hauteur). A couple of students laughed, the dean took his pen and wrote down a comment disapprovingly. As soon as I had finished, he told me: ''The joke you tried to make was really unwelcome, even calling it a joke is a nice gesture of my part''. Needless to say, this set the mood for the rest of his comments on my case study and now I'm probably seen as a bad troll by the class and the dean himself. So yeah."}
])
  const [ambigRecords, setAmbigRecords] = useState([
  {"title": "Curse of the Bean Juice", "trigger": "Ambiguity", "day": "08-24-2021", "story": "A few weeks ago I bought some dried garbanzo beans. I hate how long it takes dried beans to cook so I decided to presoak them in a canning jar. In my infinite wisdom I thought 'canned beans don't need to be refrigerated so these shouldn't be any different.' This morning I noticed there were bubbles coming out of the jar in my pantry. This is when I realized maybe I should have refrigerated them I also noticed the lid of the jar was bulging out so I knew it had some pressure built up inside. I'm guessing they started to ferment. I didn't want to open it up right away so I thought I would relive the pressure before opening to throw them away. I took a thumbtack and poked a hole in the lid of the jar. As soon as I took the tack out a geyser of shit smelling bean water shot up to my ceiling. This was the most foul smelling thing I have ever smelled and it covered my kitchen with this rancid bean juice. As I am typing this my wife has left me to clean my shame while she hides in the bathroom (the only room spared from the stink)."},
  {"title": "My dog and my phone", "trigger": "Ambiguity", "day": "09-02-2021", "story": "For context my dog is a 5 month old Greyhound cross Labrador and is very tall. She is normally well behaved, and since she was tired I left my phone on the shelf (I did not know she could reach it) to get a glass of water. I was gone for maximum 30 seconds but when I got back she was not there. At this point I had not realised that my phone was gone, so I went into the garden to check what she was doing. To my horror she had it in her mouth and was throwing it around in the garden. For some reason I thought it would be a good idea to chase after her, which of course made her run off with the phone thinking we were playing a game. Only then I thought to tell her to drop it - at which point she happened to be stood right in front of a pile of her own excrement. You can guess what happened next. She then decided to stand on it, smearing shit all over the screen. As I picked it up she gave me a look that I can only describe as a 'fuck you,' and I proceeded to spend a very long time scraping droppings off my phone."},
  {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "09-30-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."},
  {"title": "Dog and the Amazon Guy", "trigger": "Ambiguity", "day": "10-22-2021", "story": "This actually happened a few weeks ago before Halloween. I have a few of those inflatable halloween lawn decorations and typically when I turn them on and if I happen to have the front window blinds open, my dog will start barking at them since she thinks someone is coming to the house. Well, one of these evenings the blinds were open and she started barking, so to amuse her I said 'let''s go get 'em!' and I opened the front door. Unbeknownst to me, she was actually barking at an amazon delivery guy and when we went out I see a guy hauling butt back to his delivery van. I commanded my dog to stop and go back inside. I then went over to the delivery guy and profusely apologized and told him I wasn't telling my dog to go after him but rather the inflatables, as she always barks at them when I turn them on. He didn't seem too happy, but I kept apologizing for it."},
  {"title": "Toilet Flush with HR", "trigger": "Ambiguity", "day": "10-24-2021", "story": "THANKFULLY this was today so I have a suuuuper fresh recollection of it /s. I work like most people do on Mondays and decided to take my afternoon dump. I had gotten a Fair number of spam calls this morning and was on a hot streak of answering my phone to either silence or someone trying to speak to me who had nothing to do with me. While I was on the toilet, I gotten what I thought was another spam call. I should have recognized the number and realized it was my new employer (start the job in two weeks), but alas was quick to answer after killing it on candy crush. Most people would have just finished the convo on the toilet, but since I hadn't started doing the deed yet, in an effort to have the convo in a respectable area, I got off the toilet and attempted to leave the stall. I forgot that our toilets have the motion sensors that know when someone leaves and as I was exiting the stall, the toilet went off. Here comes the awkward pause from the HR person and I just move forward with the conversation."},
  {"title": "Curse of the Bean Juice", "trigger": "Ambiguity", "day": "08-24-2021", "story": "A few weeks ago I bought some dried garbanzo beans. I hate how long it takes dried beans to cook so I decided to presoak them in a canning jar. In my infinite wisdom I thought 'canned beans don't need to be refrigerated so these shouldn't be any different.' This morning I noticed there were bubbles coming out of the jar in my pantry. This is when I realized maybe I should have refrigerated them I also noticed the lid of the jar was bulging out so I knew it had some pressure built up inside. I'm guessing they started to ferment. I didn't want to open it up right away so I thought I would relive the pressure before opening to throw them away. I took a thumbtack and poked a hole in the lid of the jar. As soon as I took the tack out a geyser of shit smelling bean water shot up to my ceiling. This was the most foul smelling thing I have ever smelled and it covered my kitchen with this rancid bean juice. As I am typing this my wife has left me to clean my shame while she hides in the bathroom (the only room spared from the stink)."},
  {"title": "My dog and my phone", "trigger": "Ambiguity", "day": "09-02-2021", "story": "For context my dog is a 5 month old Greyhound cross Labrador and is very tall. She is normally well behaved, and since she was tired I left my phone on the shelf (I did not know she could reach it) to get a glass of water. I was gone for maximum 30 seconds but when I got back she was not there. At this point I had not realised that my phone was gone, so I went into the garden to check what she was doing. To my horror she had it in her mouth and was throwing it around in the garden. For some reason I thought it would be a good idea to chase after her, which of course made her run off with the phone thinking we were playing a game. Only then I thought to tell her to drop it - at which point she happened to be stood right in front of a pile of her own excrement. You can guess what happened next. She then decided to stand on it, smearing shit all over the screen. As I picked it up she gave me a look that I can only describe as a 'fuck you,' and I proceeded to spend a very long time scraping droppings off my phone."},
  {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "09-30-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."},
  {"title": "Scooby Doo", "trigger": "Ambiguity", "day": "09-30-2021", "story": "This wasn't actually today, but I recently got reminded about it so I'm posting it anyways. So when I first started meeting my gf we would watch Keeping up with the Kardashians (not my choice, but it wasn't too bad to be honest) and I'm a bit of a loud mouth I guess so I always comment on a lot of stuff I see on TV. So anyways we were just having a good time watching a random episode, and as usual I just comment on a lot of random stuff to either start a small conversation or just make her laugh. One of the Kardashians had a dog, that was named ‘Scooby’ and I just started ranting about the dogs name and the person who named the dog. Saying stuff like ‘who tf would name their dog scooby, that's so uncreative and weird’ and yada yada yada, just went on a long rant about it. Then when I was done my gf just went silent for a minute and said ‘I named my dog Scooby’. I started laughing since I thought she was joking, but quickly realized she wasn't. That was pretty awkward and I still cringe when I think about it."}
])
  const [fearRecords, setFearRecords] = useState([
  {"title": "Rude Coworkers", "trigger": "Fear", "day": "06-12-2021", "story": "Today was my first day back from 13 days of isolation. I was very sick from Covid along with 18 others from one area -- about 1/5th the workforce. The young lady who watered my plants in my lab was asking how I was doing and how I felt being back when another co-worker, a Karen-esque type, came up to us. She interrupted me to tell us how upset she is that so many people are out and how much extra work she has to do. I told her I had been out because sometimes people get sick and they need to take time off, and the mandates in our state require those who test positive to quarantine for 10 days. She then exclaimed, pointing her bony finger angrily at me, 'so, you're the damn superspreader!' I said to her 'no, I wasn't, but I heard that was your nickname in high school.' I had to visit HR after lunch. I was told my comment wasn’t appreciated and not to do it again."},
  {"title": "I missed my chance", "trigger": "Fear", "day": "09-21-2021", "story": "So this happened this summer but the full realization of what happened didn't hit me until recently. For some context I am a 20 y/o male college student and I was working a summer job which is where I met this girl. She had been working there for about 2 years with me but it wasn't until this past summer we really started to make a connection. Most of our interactions while working or on break were always great and we seemed to have a certain sort of chemistry. Then in the latter half of summer she left that job to go somewhere more related to her field of study. Before she did however, she gave me her snap so we could keep in touch which we did. For a while after she left we snapped often, mostly chatting and small talk. On more than one occasion she invited me to come over her house to hang out (she lived with her family still). Sometimes I had other prior commitments so I couldn't make it but other times I just felt too nervous about going over her house by myself that I made up excuses and stayed home. At one point she literally hit me with the ‘my parents aren't home’ bit and I completely brushed it off and claimed I had ‘something else to go to’. Anyway, we start approaching the start of school and I head back to college, but we still have been chatting in the time being. Once the first week of classes hit however, she just stopped responding to my messages. I figured she was busy with classes but after a while (several weeks) of me sending the occasional snap or ‘hey’ with no response I realized she had most likely ghosted me. I didn't grasp the severity of how bad I screwed up until I recently had a 2 am realization like we all do."},
  {"title": "Thought I was a teenager", "trigger": "Fear", "day": "10-14-2021", "story": "It was a normal day at school and the bell to get to class had rung. I was walking back up the school from my truck. It's only about 100 yards or so. As I'm nearing the school my friend rolls up in her mini van and stops to give me the bird. As friends do. As a joke, I flopped on the hood of car belly first, my feet pointing away from the school. She hit the gas and off we went. We traveled about 25 yards and I adjusted myself. She thought I was sliding off and hit the brakes. Well, she has hit them a little too hard and slid. I tried to catch myself on the top edge of the hood but missed and snagged her windshield wiper which didn't hold. So I slid off and my feet hit first. Now, I'm a fairly large guy about 200 lbs. That's alot of weight to get stopped quickly. My ankles were simply not hoss enough to handle it. My feet hit the ground and I thought I heard my boots scrape the ground, in hindsight I think it was my ankles. The area around my ankles went numb and tingly while simultaneously hurting like hell. I tumbled about 5 times hitting my elbow along the way leaving it nice and bruised. I layed out and all I could do was yell in pain. I had bilateral fractures in both of my ankles. Meaning I broke both bones in each ankle totalling out to four bones broke. According to the doc, that was the second worst type of fracture I could've gotten. I destroyed my left ankle joint with the doc pulling out a lot of bone and cartilage fragments. I'm non weight baring for 8-10 weeks. The 8 weeks mark being new years eve."},
  {"title": "My Crush is Cringe", "trigger": "Fear", "day": "10-30-2021", "story": "So this just happened an hour ago and I wanna drown myself. I (15M) had a crush in this girl we’ll call Rose. Recently I finally had the courage to confess to her how I felt and we fortunately ended things on a good note with her saying she’s not ready for a relationship and remained good friends. Things should’ve ended there right? But my stupid self decided no. Jump to today; I was working on my homework while talking to Rose. We were running out of topics to talk about, and I decided to ask ‘When do you think you’re ready for a relationship?’ She just replied she couldn’t imagine herself being in a relationship. Then she asked why I asked. Please keep in mind I was half awake as I was pretty tired. I just responded ‘Just curious, and also since you said you weren’t ready for a relationship so I was thinking I could wait for you to be ready.’ She didn’t reply for a while and 10 minutes later I decided to check our dm and as I was re reading what I sent her, I start realizing what I said was incredibly weird. I decided to delete the message and changed my reply to ‘Donno just curious’ Since discord is an asshole, they don’t show if the other person had read the message or not. So I was hoping she didn’t see it, but I knew I was too far late. I told our mutual friend about it and they said she read it. My. Heart. Stopped. I just wanted to die.. I probably made things worse for us and she wasn’t going to see me the same way ever again. I’ve been typing this out and thinking what I should do. She did reply to me like she didn’t see what happened.. so now im fully awake.. not sure what to do.. I’ll keep you guys updated if anything happens if ya’ll interested Anyways thanks for reading."}
])
  const [goalsRecords, setGoalsRecords] = useState([
  {"title": "Diffusing with Humor Fail", "trigger": "Goals", "day": "10-13-2021", "story": "Long story short, my dumbass self thought it would be a great idea to be the funny guy and deliberately put a slightly offensive joke in an oral case study presented to the dean. At some point I was talking about dwarf people and the discriminations they're facing, so I added: ‘they're often accused of not measuring up’. (Measuring...they're of short height...got it?). It loses a bit of meaning when translated. IMO it was funnier in French (''on les accuse souvent de ne pas être à la hauteur). A couple of students laughed, the dean took his pen and wrote down a comment disapprovingly. As soon as I had finished, he told me: ''The joke you tried to make was really unwelcome, even calling it a joke is a nice gesture of my part''. Needless to say, this set the mood for the rest of his comments on my case study and now I'm probably seen as a bad troll by the class and the dean himself. So yeah."},
  {"title": "Where are my keys?", "trigger": "Goals", "day": "10-29-2021", "story": "I work at a doggy daycare in and there’s this one small older dog that we walk for about 15 minutes every day. He has a set of keys we need to use to walk him and if we don’t walk him we get in big trouble with the parents. While normally he only had one walk, today he had two. My shift ended before the second walk so another person was going to do it until they noticed they were missing the keys and texted me. My friend and I had been planning going to a Korean bbq place that has a 30 minute time limit for a while now and I got the text from work 5 minutes after we started eating. The place cost 40 dollars per person plus additional beverages and tip so if I left then I wouldn’t be able to make it in time back as I would be using public transport. It’s also the first time I’ve seen my friend in a month and a half. After a back and forth with my manager and another coworker I thought I would be able to drop it off later on as the coworker told me this but then I got called by my boss who then ordered an Uber so that I could send back the key in my bag despite me saying I could leave immediately. I feel terrible and although I was told that mistakes happen by my boss, the manager did not respond to my further messages so now I believe she highly dislikes me. I was told by someone else that I am already disliked for being picky or bossy so now I’m sure that there is not a single person at work that doesn’t dislike me. I’m also scared for the sanctity of my job."},
  {"title": "Diffusing with Humor Fail", "trigger": "Goals", "day": "10-13-2021", "story": "Long story short, my dumbass self thought it would be a great idea to be the funny guy and deliberately put a slightly offensive joke in an oral case study presented to the dean. At some point I was talking about dwarf people and the discriminations they're facing, so I added: ‘they're often accused of not measuring up’. (Measuring...they're of short height...got it?). It loses a bit of meaning when translated. IMO it was funnier in French (''on les accuse souvent de ne pas être à la hauteur). A couple of students laughed, the dean took his pen and wrote down a comment disapprovingly. As soon as I had finished, he told me: ''The joke you tried to make was really unwelcome, even calling it a joke is a nice gesture of my part''. Needless to say, this set the mood for the rest of his comments on my case study and now I'm probably seen as a bad troll by the class and the dean himself. So yeah."}
])
  const [rundownRecords, setRundownRecords] = useState([
  {"title": "My dog won't look at me", "trigger": "Rundown", "day": "05-06-2021", "story": "This started a few weeks ago. I had a friend and her kids stay with me and my wife for a few days. Hadn’t seen them in awhile and they had never been to Texas (we are from California and they are originally from Thailand but we met in California years back). We showed them some of the unique things about Texas eg bbq, bucees, etc. Anyway while they were here we started talking about eating different things from different countries and she asks if I have ever eaten bugs. I have but only once but I’m open to try anything once. Fast forward to this morning. I’m laying in bed and my wife goes to get the mail. She hands me a padded envelope and says it’s from (friend). No idea what it could be so I tear open the package. Our dog was very interested btw. I get a smell like nuts so I’m thinking ‘strange she would send me nuts’ when a few fall out onto my shirtless torso and on the bed. They’re very black and now I’m more confused. Then I focus on one and I realize it’s a cricket body. She sent me fried crickets. One of the bags must have broken open in transit so they’re falling all over the place and my wife is losing her SHIT screaming about bugs in the bed. I am laughing hysterically picking cricket parts out of my chest hair while she runs away making a combination of screaming, laughing, and gagging sounds."},
  {"title": "The freaking fire alarm", "trigger": "Rundown", "day": "09-16-2021", "story": "I’m a senior in college and live with 2 other girls in a student only apartment off campus. For whatever reason I never outgrew wetting the bed and do it almost every night. Up until today I’ve done a pretty good job at hiding it. I change into a diaper at night in my own room and in the morning I stash the used diaper in a large bag I and throw it out in the apartment complex dumpster on my way out. No one other than my ex boyfriend has ever found out about my issues. I live in a hot state and it gets warm at night, no one sees me so I wore these little booty shorts and a tank top to bed. Then, at 3:00 am the fire alarm goes off. I wake up groggy and hear people evacuating the building, and me and my roommates start to head outside too. It’s not until I’m almost out the door that I realize what I’m wearing. Keep in mind, these are not Depend that advertise how discreet they are under yoga pants. These are made for bedwetting. They’re geriatric, tape-on incredibly thick and high waisted diapers, and not to be gross but it was wet too which makes it thicker. The waistband was peeking above my pants and the bulk clearly showed through the thin fabric of my shorts. I tried to yank my tank top down as far as I could, but it still didn’t meet the waistband of my shorts. I thought if I didn’t draw attention to it, maybe no one would notice. That is until I heard a guy in a group of about 10 people behind me whisper “I think that chicks wearing a diaper” a couple of people did a light gasp and giggle and I heard one girl say “oh my god, not so loud, she must be so embarrassed.” I turned around instinctively at the group and one girl said to me “cute shorts” and a couple more of them giggled. I was beyond humiliated and turned bright red. That’s when my roommates both looked down and saw the mess that was my lower half. One of them went silent and her eyes went as wide as saucers. My other roommate took off her robe (she was also wearing pajamas) and handed it to me and said “here you look really cold.” I then put on the robe and waited what seemed like an eternity until they let us in the building. As I was walking upstairs I heard someone below us in that same group ask “so was that girl seriously wearing a diaper” and someone responded “yeah I think she was. This happened a couple days ago and no one has said anything to me sense, but I have never been so embarrassed in my life."},
  {"title": "Kung Fu Embarassment", "trigger": "Rundown", "day": "10-09-2021", "story": "So this happened in 2015 i was 9 years old i joined a kung fu academy because i liked martial arts so basically what happened is that i used to excercise in tracksuit before in kung fu class i excitedly bought a new uniform for my class so the first day of class with uniform we doing some sort of strectching there were girls behind me and suddenly i hear a ‘tsshhhhhhh’ sound i was like Wtf but i kept stretching i heard girls behind me laughing i thought maybe they were laughin bout somethin else suddenly they called the teacher and he suddenly stopped me cuz my ass was showing from behind and he says me to go rest i said’ why' he says : ‘go rest its enough ‘ OnLy Me i was likeee WTF suddenly he called my parents and told him and then i got to know what that ‘tsshhh’ sound was he got me home i was crying with embarassment . But i still had the courage to back to class days later."},
  {"title": "Blanket Confusion", "trigger": "Rundown", "day": "10-22-2021", "story": "Yesterday I went to a fabric store and I was in a hurry to get home because I was tired and was up all night so I just wanted to get in and get out but of all the days this small fabric store had to be busy it was today so I go in I get my fabric and realize I got the wrong one so I go back get my fabric again and grab a number I was 86 the were on 84 not so bad but no the lady in front of me had a cart full of Blanket fabric so she needs a lot so I wait in line for like ten minutes she still not done so I text my friend if this lady doesn’t hurry up Going to cuss her out so as I was about to lose my mind when they open a new register so I head on over and hear ‘I’m making blankets for foster kids’"},
  {"title": "Dangerous Stir Fry", "trigger": "Rundown", "day": "10-27-2021", "story": "Late last night I ate a stir fry and there was this massive bit of brocolli and I just wolfed it down forgetting to chew. It gets stuck in my throat and I start to choke but as if that's not bad enough this bit of brocolli is absolutely roasting and its hurting so much. I start to panic and look for some water or juice in a glass around me but of course there is none cause I'm an idiot and was so focused on getting the food down me as soon as possible I hadn't bothered to get a drink. So I stumble towards the kitchen, tripping over the coffee table and knocking everything flying, my life flashing before my eyes, I smash down the corridor bumping into everything possible, throwing myself into the kitchen I grab a glass of water and after a few attempts manage to slowly swallow this absolutely boiling, massively painful, stupidly chunky piece of brocolli down my throat. I catch my breath, I calm down, I stare at the floor for a while hanging my head, I clean up my mess and I go to bed. All day today I can feel my throat is burnt. Its sore inside and my voice is a little raspy. I knew its possible to choke on your food but I didn't know I could badly burn the inside of my throat. Always remember to chew folks. I think I'll be obsessively blowing on my food before I eat it for the rest of my life now…"},
  {"title": "Dangerous Stir Fry", "trigger": "Rundown", "day": "10-27-2021", "story": "Late last night I ate a stir fry and there was this massive bit of brocolli and I just wolfed it down forgetting to chew. It gets stuck in my throat and I start to choke but as if that's not bad enough this bit of brocolli is absolutely roasting and its hurting so much. I start to panic and look for some water or juice in a glass around me but of course there is none cause I'm an idiot and was so focused on getting the food down me as soon as possible I hadn't bothered to get a drink. So I stumble towards the kitchen, tripping over the coffee table and knocking everything flying, my life flashing before my eyes, I smash down the corridor bumping into everything possible, throwing myself into the kitchen I grab a glass of water and after a few attempts manage to slowly swallow this absolutely boiling, massively painful, stupidly chunky piece of brocolli down my throat. I catch my breath, I calm down, I stare at the floor for a while hanging my head, I clean up my mess and I go to bed. All day today I can feel my throat is burnt. Its sore inside and my voice is a little raspy. I knew its possible to choke on your food but I didn't know I could badly burn the inside of my throat. Always remember to chew folks. I think I'll be obsessively blowing on my food before I eat it for the rest of my life now…"},
  {"title": "The freaking fire alarm", "trigger": "Rundown", "day": "11-01-2021", "story": "I’m a senior in college and live with 2 other girls in a student only apartment off campus. For whatever reason I never outgrew wetting the bed and do it almost every night. Up until today I’ve done a pretty good job at hiding it. I change into a diaper at night in my own room and in the morning I stash the used diaper in a large bag I and throw it out in the apartment complex dumpster on my way out. No one other than my ex boyfriend has ever found out about my issues. I live in a hot state and it gets warm at night, no one sees me so I wore these little booty shorts and a tank top to bed. Then, at 3:00 am the fire alarm goes off. I wake up groggy and hear people evacuating the building, and me and my roommates start to head outside too. It’s not until I’m almost out the door that I realize what I’m wearing. Keep in mind, these are not Depend that advertise how discreet they are under yoga pants. These are made for bedwetting. They’re geriatric, tape-on incredibly thick and high waisted diapers, and not to be gross but it was wet too which makes it thicker. The waistband was peeking above my pants and the bulk clearly showed through the thin fabric of my shorts. I tried to yank my tank top down as far as I could, but it still didn’t meet the waistband of my shorts. I thought if I didn’t draw attention to it, maybe no one would notice. That is until I heard a guy in a group of about 10 people behind me whisper “I think that chicks wearing a diaper” a couple of people did a light gasp and giggle and I heard one girl say “oh my god, not so loud, she must be so embarrassed.” I turned around instinctively at the group and one girl said to me “cute shorts” and a couple more of them giggled. I was beyond humiliated and turned bright red. That’s when my roommates both looked down and saw the mess that was my lower half. One of them went silent and her eyes went as wide as saucers. My other roommate took off her robe (she was also wearing pajamas) and handed it to me and said “here you look really cold.” I then put on the robe and waited what seemed like an eternity until they let us in the building. As I was walking upstairs I heard someone below us in that same group ask “so was that girl seriously wearing a diaper” and someone responded “yeah I think she was. This happened a couple days ago and no one has said anything to me sense, but I have never been so embarrassed in my life."}
])
  const [colors, setColors] = useState({"Ambiguity": "#B56B9A", "Fear": "#E3C6DF", "Goals": "#5DACCE", "Rundown": "#5C83CE"});
  const [currScreen, setCurrScreen] = useState("Home");

  let handleScreenChange = ({ screen }) => {
    setCurrScreen(screen);
  };

   return (
      <View style={styles.container}>
        {currScreen == "Home" && <View style={styles.container}><ScrollView>
        <View style={styles.hello}>
          <Text style={styles.opening}>Hello Sam,</Text>
          <Text style={styles.opening}>What is your concern today?</Text>
        </View>
          <View style={styles.graph}>
            <Circles total={totalRecords.length} ambig={ambigRecords.length} fear={fearRecords.length} goals={goalsRecords.length} rundown={rundownRecords.length}/>
         </View>
         <TouchableOpacity style={styles.startButton} onPress={() => {setCurrScreen("Dialogue")}}>
            <Text style={styles.startButtonText}> Share your concerns </Text>
          </TouchableOpacity>
          <Diary records={totalRecords} colors={colors}/>
          </ScrollView>
          </View>}
          {currScreen == "Dialogue" && <View>
            <Dialogue changeScreen={handleScreenChange}/>
          </View>
          }
      </View>
   );
}
export default App;

const styles = StyleSheet.create({
    container: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      alignContent: "center"
    },
    hello: {
      height: 100,
      marginLeft: 15,
      marginTop: 60,
    },
    opening: {
      fontWeight: "bold",
      fontSize: 20
    },
    record: {
      justifyContent: "flex-start"
    },
    graph: {
      height: 200,
      marginBottom: 80,
      marginTop: 0,
    },
    startButton: {
      width: 280,
      height: 35,
      textTransform: "none",
      backgroundColor: "#3E4449",
      display: "flex",
      justifyContent: "center",
      alignSelf: "center",
      borderRadius: 4,
      marginTop: 80
    },
    startButtonText: {
      color: "white",
      alignSelf: "center"
    }
  });